before:
  hooks:
    - go mod tidy
    -
builds:
  - binary: seamoon
    env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X github.com/DVKunion/SeaMoon/system/xlog.Version={{.Version}} -X github.com/DVKunion/SeaMoon/system/xlog.Commit={{.Sha}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag  }}-next"
upx:
  - enabled: true
    goos: [linux, darwin]
    compress: best
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'