before:
  hooks:
    - go mod tidy
builds:
  - binary: seamoon
    env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X github.com/DVKunion/SeaMoon/pkg/consts.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag  }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'