name: SeaMoon

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone seamoon-web repository
        uses: actions/checkout@v4
        with:
          repository: 'DVKunion/seamoon-web'
          ref: 'main'  # Or any other branch or tag you want to checkout
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: Build Front
        run: |
          npm run build
          cp -r dist /tmp
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build
        run: |
          cp -r /tmp/dist cmd/client/static
          go mod tidy
          go build -o seamoon -v --ldflags "-s -w -X github.com/DVKunion/SeaMoon/pkg/consts.Version=${{github.ref_name}} -X github.com/DVKunion/SeaMoon/pkg/consts.Commit=${{github.sha}}" cmd/main.go
      - uses: actions/upload-artifact@v4
        with:
          path: seamoon