name: seamoon-build
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Front
        run: |
          cd web && npm install | true && npm run build && cp -r dist ../cmd/client/static
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build
        run: |
          go mod tidy
          go build -o seamoon -v --ldflags "-s -w -X github.com/DVKunion/SeaMoon/pkg/system/xlog.Version=${{github.ref_name}} -X github.com/DVKunion/SeaMoon/pkg/system/xlog.Commit=${{github.sha}}" cmd/main.go
      - uses: actions/upload-artifact@v4
        with:
          path: seamoon
  build-docker:
    name: build-docker
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        name: login docker.io
        with:
          registry: "docker.io"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Front
        run: |
          cd web && npm install | true && npm run build && cp -r dist ../cmd/client/static
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            docker.io/dvkunion/seamoon:latest
            docker.io/dvkunion/seamoon:${{github.ref_name}}
          build-args: |
            VERSION=${{github.ref_name}}
            SHA=${{github.sha}}
          context: ./