name: Package
on:
  push:
    tags:
      - "*"

jobs:
  package-docker:
    name: package-docker
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - registry: docker.io
            repo: dvkunion/seamoon
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          - registry: [
            registry.cn-hangzhou.aliyuncs.com,
            registry.cn-shanghai.aliyuncs.com,
            registry.cn-qingdao.aliyuncs.com,
            registry.cn-beijing.aliyuncs.com,
            registry.cn-zhangjiakou.aliyuncs.com,
            registry.cn-huhehaote.aliyuncs.com,
            registry.cn-shenzhen.aliyuncs.com,
            registry.cn-chengdu.aliyuncs.com,
            registry.cn-hongkong.aliyuncs.com,
            registry.ap-northeast-1.aliyuncs.com,
            registry.ap-southeast-1.aliyuncs.com,
            registry.ap-southeast-2.aliyuncs.com/seammon/seamoon",
            registry.ap-southeast-3.aliyuncs.com,
            registry.ap-southeast-5.aliyuncs.com,
            registry.ap-south-1.aliyuncs.com,
            registry.eu-central-1.aliyuncs.com,
            registry.eu-west-1.aliyuncs.com,
            registry.us-west-1.aliyuncs.com,
            registry.us-east-1.aliyuncs.com,
          ]
            repo: seamoon/seamoon
            username: ${{ secrets.ALIYUN_USERNAME }}
            password: ${{ secrets.ALIYUN_PASSWORD }}
          - registry: [
            hkccr.ccs.tencentyun.com,
            inccr.ccs.tencentyun.com,
            sgccr.ccs.tencentyun.com,
            thccr.ccs.tencentyun.com,
            krccr.ccs.tencentyun.com,
            jpccr.ccs.tencentyun.com,
            deccr.ccs.tencentyun.com,
            useccr.ccs.tencentyun.com,
            uswccr.ccs.tencentyun.com,
          ]
            repo: seamoon/seamoon
            username: ${{ secrets.TENCENT_USERNAME }}
            password: ${{ secrets.TENCENT_PASSWORD }}
          - registry: [
            ccr.ccs.tencentyun.com,
          ]
            repo: dvkunion/seamoon
            username: ${{ secrets.TENCENT_USERNAME }}
            password: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        name: login ${{ matrix.registry }}
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            ${{ matrix.registry }}/${{ matrix.repo }}:latest
            ${{ matrix.registry }}/${{ matrix.repo }}:${{github.ref_name}}
          build-args: |
            VERSION=${{github.ref_name}}
          context: ./