name: Package
on:
  push:
    tags:
      - "*"

jobs:
  package-docker:
    name: package-docker
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            dvkunion/seamoon-client:latest
            dvkunion/seamoon-client:${{github.ref_name}}
          build-args: |
            VERSION=${{github.ref_name}}
          context: ./